/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import React, { useRef } from "react";

//for controlling helix rotation speed
const HELIX_SPEED = 6; //speed of the scrolling to be defined here

//main airplane component that renders 3D airplane model
export function Airplane(props) {
  //extract nodes and materials from the 3D model
  const { nodes, materials } = useGLTF("model/to/be/imported/here");

  // reference to the helix mesh for animation
  const helix = useRef();

  // animate helix rotation on each frame
  useFrame((_state, delta) => {
    helix.current.rotation.x += delta * HELIX_SPEED;
  });

  // render the 3D airplane model
  return (
    <group {...props} dispose={null}>
      {/* render main airplane body */}
      <mesh
        geometry={nodes.PUSHILIN_Plane_Circle000.geometry}
        material={materials.plane}
      />
      {/* render rotating helix with position offset */}
      <mesh
        ref={helix}
        geometry={nodes.PUSHILIN_Plane_Helix.geometry}
        material={materials.plane}
        position={[1.09, 0.23, 0]}
      />
    </group>
  );
}

// preload the 3D model to improve performance
useGLTF.preload("model/to/be/imported/here");