/* 
auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";
export function Cloud({ opacity, ...props }) {
  // extract nodes and materials from the 3D model
  const { nodes, materials } = useGLTF("./model/to/be/imported/here");
  return (
    // group wrapper for the cloud mesh
    <group {...props} dispose={null}>
      {/* render cloud mesh with geometry from the model */}
      <mesh geometry={nodes.Node.geometry}>
        {/* apply standard material with transparency */}
        <meshStandardMaterial
          {...materials["lambert2SG.001"]}
          transparent
          opacity={opacity}
        />
      </mesh>
    </group>
  );
}

// preload the cloud model to improve performance
useGLTF.preload("./model/to/be/imported/here");